SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_MIN_ANGLE = 20
ASTEROID_MAX_ANGLE = 50
ASTEROID_EXPLOSION_TIME = 0.5 # second

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOT_SPEED = 500
PLAYER_SHOOT_CD = 0.3

SHOT_RADIUS = 5

UI_OFFSET = 10

GAME_RUNNING = "running"
GAME_OVER = "game over"
